export const filterItems = [
  { title: "RECOMMENDED COLUMN", subtitle: "オススメ" },
  { title: "RECOMMENDED DIET", subtitle: "ダイエット" },
  { title: "RECOMMENDED BEAUTY", subtitle: "美容" },
  { title: "RECOMMENDED HEALTH", subtitle: "健康" },
]


export const columnCardData = [
  {
    image: "/photos/column-1.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-2.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-3.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-4.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-5.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-6.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-7.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-8.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-1.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-2.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-3.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-4.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-5.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-6.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-7.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
  {
    image: "/photos/column-8.jpg",
    date: "2021.05.17",
    time: "23:25",
    title: "魚を食べて頭もカラダも元気に！\n知っておきたい魚を食べるメリ…",
    tags: ["魚料理", "和食", "DHA"],
  },
];